### ISSUE TITLE
it doesn't support arabic language

### ISSUE THREAD

**Issue by joukhar** [opcodesio/log-viewer#345] opened 2024-03-03 12:34 UTC
```php

  "RESPONSE": "{\"success\":false,\"message\":\"\\u0643\\u0644\\u0645\\u0629 \\u0627\\u0644\\u0645\\u0631\\u0648\\u0631 \\u0627\\u0644\\u0642\\u062f\\u064a\\u0645\\u0629 \\u0644\\u0627 \\u062a\\u062a\\u0637\\u0627\\u0628\\u0642 \\u0645\\u0639 \\u0643\\u0644\\u0645\\u0629 \\u0627\\u0644\\u0645\\u0631\\u0648\\u0631 \\u0627\\u0644\\u062e\\u0627\\u0635\\u0629 \\u0628\\u0643\"}",
```

**Comment by arukompas** [comment] 2024-03-04 06:24
hey @joukhar , please share the log file, and a screenshot of how it appears in Log Viewer.

**Comment by joukhar** [comment] 2024-03-04 09:06
@arukompas 
![Screenshot from 2024-03-04 10-01-55](https://github.com/opcodesio/log-viewer/assets/94228259/95df3d0c-473a-4541-be57-fd1b3f53252e)

**Comment by arukompas** [comment] 2024-03-05 04:32
hey @joukhar , thanks for the screenshot. How about the log **file** itself? It could be that the content is stored in the log file like this, therefore there's nothing for the Log Viewer to do and it just displays the content inside the `api-requests.log` file.

**Comment by joukhar** [comment] 2024-03-05 09:10
nah , it returns translated string from /lang/ar.json , and i used dd()

**Comment by arukompas** [comment] 2024-03-05 11:13
@joukhar could you share the contents of the `storage/logs/api-requests.log` file?

**Comment by joukhar** [comment] 2024-03-06 20:21
```
[2024-03-06 18:06:32] production.ERROR: Api Request {"URL":"PRIVATE","METHOD":"POST","USER_AGENT":"PRIVATE","IP":"PRIVATE","USER":"PRIVATE","REQUEST_BODY":{"id":"PRIVATE","answers":"PRIVATE","totalTime":44},"RESPONSE":"{\"success\":false,\"message\":\"\\u062d\\u062f\\u062b \\u062e\\u0637\\u0623 \\u0645\\u0627\"}","LOCALE":"ar"} 
```
i use ai for this because im lazy to come with solution, it easy but u just need to convert readable text.

The Arabic text for "\u062d\u062f\u062b \u062e\u0637\u0623 \u0645\u0627" is "حدث خطأ ما".

**Comment by arukompas** [comment] 2024-03-07 06:24
@joukhar ok, but that's what I mean. The log message is logged as characters `\u062d\u062f\u062b \u062e\u0637\u0623 \u0645\u0627` inside the `api-requests.log` file, not as arabic unicode characters.

Log Viewer just displays whatever's inside the file and it should not do any kind of hex-to-unicode conversion because that would be misleading to what is actually logged in the file.

The issue is somewhere else, because it's not saving arabic characters into the log file itself. Perhaps the API itself is returning non-arabic characters (`\u062d\u062f\u062b \u062e\u0637\u0623 \u0645\u0627`).

**Comment by arukompas** [comment] 2024-03-07 13:13
@joukhar the easiest way is to just open your `api-requests.log` file inside a text editor. If it does not contain arabic characters inside a simple text editor, then Log Viewer won't display them either.

**Comment by joukhar** [comment] 2024-03-07 20:51
You're right i tested it on vscode and it doesn't show proper arabic , the problem is in json requests

**Comment by arukompas** [comment] 2024-03-08 07:54
@joukhar awesome, thanks for confirming! 😃 closing

**Closed by arukompas** 2024-03-08 07:54 UTC
