### ISSUE TITLE
Log Viewer doesn't work with Laravel VUE Spa application.

### ISSUE THREAD

**Issue by mrkazmierczakuw** [opcodesio/log-viewer#77] opened 2022-09-03 22:59 UTC
This log viewer should work properly regardless of the frontend technologies used. It should be an independent link showing logs regardless of the packages and technologies used in the project

[Vue Router warn]: No match found for location with path "/log-viewer"

**Comment by arukompas** [comment] 2022-09-04 04:12
Hey @mrkazmierczakuw 

This package is independent from any frontend libraries used, because it comes with its own frontend built in.

But this also means it's not specifically a Vue package, so you cannot call this route within the Vue Router, because Vue Router expects a Vue component.

**The fix:** just do a plain redirect using the anchor tag instead:
```html
<a href="/log-viewer">Laravel logs</a>
```

Hope this helps! :)

**Comment by arukompas** [comment] 2022-09-04 04:18
Closing as it's not a bug and works as expected.

**Closed by arukompas** 2022-09-04 04:18 UTC
