### ISSUE TITLE
No publishable resources for tag [laravel-assets].

### ISSUE THREAD

**Issue by lly0414** [opcodesio/log-viewer#85] opened 2022-09-05 10:44 UTC
```
> @php artisan vendor:publish --tag=laravel-assets --ansi
No publishable resources for tag [laravel-assets].
```
I finally got this problem when I installed it with composer, there is no livewire directory in public!

**Comment by arukompas** [comment] 2022-09-05 11:06
@lly0414  hey! You don't need to run this command for Log Viewer to work.

Is this something that you've configured manually in the `composer.json` file? I haven't seen this exact command before.

**Comment by EdgedSheet** [comment] 2022-09-06 07:24
> @lly0414 hey! You don't need to run this command for Log Viewer to work.
> 
> Is this something that you've configured manually in the `composer.json` file? I haven't seen this exact command before.

It's something default. When you install something with composer it will automatically try to run that command.

![capture](https://user-images.githubusercontent.com/110625050/188571435-7088b5b5-32f7-4934-88d9-bd8fe26f8454.PNG)

Laravel automatically tries to publish new assets you have when installing or updating new packages. If there are not any new assets found you'll get that message.

```
No publishable resources for tag [laravel-assets].
```

It's not a problem or error, it's an info message. So you can completely ignore it.

Just publish the config after installing the packag and that's all.

```
php artisan vendor:publish --tag="log-viewer-config"
```

**Comment by arukompas** [comment] 2022-09-06 07:26
Thanks for the explanation @EdgedSheet !

This package doesn't have any resources that must be published upon installation, so it's not a bugs. The config is optional.

Closing as it's not a bug.

**Closed by arukompas** 2022-09-06 07:26 UTC
