### ISSUE TITLE
unserialize(): Error at offset 0 of 81 bytes

### ISSUE THREAD

**Issue by irtzamazhar** [opcodesio/log-viewer#346] opened 2024-03-07 08:50 UTC
After setting up this package I faced `unserialize(): Error at offset 0 of 81 bytes` every time I reloaded my **log-viewer** route. It's working first time but if I refresh my page I get that error. 
After some googling, I got a solution and to regenerate `APP_KEY` will resolve it but still, if I refresh my page I get that issue.

![image](https://github.com/opcodesio/log-viewer/assets/24386185/74773742-6400-4747-97a5-b8a03d73d7e1)

**Comment by ikisen** [comment] 2024-03-07 12:07
Are you able to reproduce this issue in a blank Laravel environment with just the log-viewer package installed? It looks like this error comes from your project / middleware configuration. Try disabling all your middlewares or any code executed before the route action is resolved.

**Comment by MujeebAnwar** [comment] 2024-03-08 13:33
@irtzamazhar If you're not using Sanctum, you have to disable the EnsureFrontendRequestsAreStateful middleware in config/log-viewer.php. This middleware utilizes Sanctum's encrypt_cookies middleware if available; otherwise, it defaults to Laravel's EncryptCookies middleware. In Laravel's EncryptCookies middleware, serialize is false by default.

**Comment by MNhat0308** [comment] 2024-03-09 15:49
what if i use sanctum , error will show again?
@irtzamazhar

**Comment by MNhat0308** [comment] 2024-03-21 09:55
In middle EncryptCookies file  set ` protected static $serialize = false;` to false and it work well

**Comment by arukompas** [comment] 2024-08-16 10:52
This seems to be an issue when using Sanctum, correct? Not sure why cookie serialization & deserialization fails, but it can be fixed by disabling serialization in `EncryptCookies` middleware, like mentioned above.

Closing the issue.

**Closed by arukompas** 2024-08-16 10:52 UTC
