### ISSUE TITLE
Log viewer page expired  419 in laravel 9 app

### ISSUE THREAD

**Issue by Merite15** [opcodesio/log-viewer#182] opened 2023-01-12 13:34 UTC
I have a laravel 9 application as an api and I am trying to use your package to see my logs but after installation I have a 419 page expired error.
How can I fix this

**Comment by arukompas** [comment] 2023-01-12 17:12
Hey @Merite15 ,

How are you accessing the Log Viewer? When does this error happen, after what action?

at the moment the Log Viewer can only be viewed via browser (not API access), so you'll need to make sure that your application still has the default `web` middleware group (defined in the `app/Http/Kernel.php` file), which is automatically applied to Log Viewer.

I can help more if you can share the contents of your `app/Http/Kernel.php` and `config/log-viewer.php` files.

**Comment by Merite15** [comment] 2023-01-12 21:19
there is my app/Http/kernel.php content:
?php

namespace App\Http;

use App\Http\Middleware\DynamicDB;
use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array<int, class-string|string>
     */
    protected $middleware = [
        // \App\Http\Middleware\TrustHosts::class,
        \App\Http\Middleware\TrustProxies::class,
        \Illuminate\Http\Middleware\HandleCors::class,
        \App\Http\Middleware\PreventRequestsDuringMaintenance::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array<string, array<int, class-string|string>>
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],

        'api' => [
            \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
            'throttle:api',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];

    /**
     * The application's route middleware.
     *
     * These middleware may be assigned to groups or used individually.
     *
     * @var array<string, class-string|string>
     */
    protected $routeMiddleware = [
        'auth' => \App\Http\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'auth.session' => \Illuminate\Session\Middleware\AuthenticateSession::class,
        'cache.headers' => \Illuminate\Http\Middleware\SetCacheHeaders::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'password.confirm' => \Illuminate\Auth\Middleware\RequirePassword::class,
        'signed' => \App\Http\Middleware\ValidateSignature::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'verified' => \Illuminate\Auth\Middleware\EnsureEmailIsVerified::class,
        'dynamicDB' => DynamicDB::class,
    ];
}

**Comment by Merite15** [comment] 2023-01-12 21:20
I doesn't have a log-viewer file in config directory

**Comment by arukompas** [comment] 2023-01-13 06:32
Hey @Merite15 , I can't reproduce the issue.

Your Http/Kernel setup is standard, and I've copied your configuration to a fresh new Laravel 9 project and it works as expected, the Log Viewer loads in the browser and all actions work:

<img width="1728" alt="Screenshot 2023-01-13 at 08 29 24" src="https://user-images.githubusercontent.com/8697942/212252839-dde065d1-cff4-4e9f-ac75-1bba3e70171b.png">

Can you share the screenshot of the error you're receiving? And explain the steps you took before the error?

**Comment by Merite15** [comment] 2023-01-13 12:38
My computer is a macbook and when i call localhost:8000/log-viewer in route http://localhost:8000/livewire/message/log-viewer::log-list i have a 419 error
![anydesk00000](https://user-images.githubusercontent.com/86039889/212322109-54586ef5-cea9-4cf3-b5d8-aa0f7ec1d269.png)

**Comment by Merite15** [comment] 2023-01-13 12:38
![anydesk00000](https://user-images.githubusercontent.com/86039889/212322222-2dfcbbd9-94e4-453d-b3fb-ddeef92eef26.png)

**Comment by Merite15** [comment] 2023-01-13 12:45
My computer is a macbook and when i call localhost:8000/log-viewer in route http://localhost:8000/livewire/message/log-viewer::log-list i have a 419 error
![anydesk00000](https://user-images.githubusercontent.com/86039889/212323221-a9cc4c0d-5f23-462e-a0af-2487edac4896.png)

**Comment by arukompas** [comment] 2023-01-14 10:38
Hey @Merite15 , **are cookies disabled in the browser?
**

Cookies are required to keep a session active and this to keep the Log Viewer working properly.

I don't see any "Cookie" or "Set-Cookie" header in the response, that's why I'm asking. This would also explain why this is happening.

**Comment by myfender** [comment] 2023-02-04 08:07
I have the same error on my mac in localhost, on my vps it works without problem

<img width="2046" alt="Screenshot 2023-02-04 at 09 04 49" src="https://user-images.githubusercontent.com/3018311/216756428-7f096a33-4eff-400d-95ca-68534fee19d8.png">

**Comment by arukompas** [comment] 2023-02-21 06:54
Hey all, I've just released v2 of the Log Viewer without the Livewire dependency. It should now work a lot better and in more environments.

Read more about the v2 release and how to upgrade here - https://arunas.dev/log-viewer-v2/

Closing this for now. If you still have issues with v2, please open a new issue. Thanks! 😀

**Closed by arukompas** 2023-02-21 06:54 UTC
